import { Notes } from "./Notes";
import { Octaves } from "./Octaves";

export const keys = [
  {
    index: 1,
    key: 0,
    octave: Octaves.First,
    note: Notes[0],
    sound: require("../assets/sounds/new/C1.mp3"),
  },
  {
    index: 13,
    key: 1,
    octave: Octaves.Second,
    note: Notes[0],
    sound: require("../assets/sounds/new/C2.mp3"),
  },
  {
    index: 25,
    key: 2,
    octave: Octaves.Third,
    note: Notes[0],
    sound: require("../assets/sounds/new/C3.mp3"),
  },
  {
    index: 37,
    key: 3,
    octave: Octaves.Fourth,
    note: Notes[0],
    sound: require("../assets/sounds/new/C4.mp3"),
  },
  {
    index: 49,
    key: 4,
    octave: Octaves.Fifth,
    note: Notes[0],
    sound: require("../assets/sounds/new/C5.mp3"),
  },
  {
    index: 61,
    key: 5,
    octave: Octaves.Sixth,
    note: Notes[0],
    sound: require("../assets/sounds/new/C6.mp3"),
  },
  {
    index: 2,
    key: 6,
    octave: Octaves.First,
    note: Notes[1],
    sound: require("../assets/sounds/new/Db1.mp3"),
  },
  {
    index: 14,
    key: 7,
    octave: Octaves.Second,
    note: Notes[1],
    sound: require("../assets/sounds/new/Db2.mp3"),
  },
  {
    index: 26,
    key: 8,
    octave: Octaves.Third,
    note: Notes[1],
    sound: require("../assets/sounds/new/Db3.mp3"),
  },
  {
    index: 38,
    key: 9,
    octave: Octaves.Fourth,
    note: Notes[1],
    sound: require("../assets/sounds/new/Db4.mp3"),
  },
  {
    index: 50,
    key: 10,
    octave: Octaves.Fifth,
    note: Notes[1],
    sound: require("../assets/sounds/new/Db5.mp3"),
  },
  {
    index: 62,
    key: 11,
    octave: Octaves.Sixth,
    note: Notes[1],
    sound: require("../assets/sounds/new/Db6.mp3"),
  },
  {
    index: 3,
    key: 12,
    octave: Octaves.First,
    note: Notes[2],
    sound: require("../assets/sounds/new/D1.mp3"),
  },
  {
    index: 15,
    key: 13,
    octave: Octaves.Second,
    note: Notes[2],
    sound: require("../assets/sounds/new/D2.mp3"),
  },
  {
    index: 27,
    key: 14,
    octave: Octaves.Third,
    note: Notes[2],
    sound: require("../assets/sounds/new/D3.mp3"),
  },
  {
    index: 39,
    key: 15,
    octave: Octaves.Fourth,
    note: Notes[2],
    sound: require("../assets/sounds/new/D4.mp3"),
  },
  {
    index: 51,
    key: 16,
    octave: Octaves.Fifth,
    note: Notes[2],
    sound: require("../assets/sounds/new/D5.mp3"),
  },
  {
    index: 63,
    key: 17,
    octave: Octaves.Sixth,
    note: Notes[2],
    sound: require("../assets/sounds/new/D6.mp3"),
  },
  {
    index: 4,
    key: 18,
    octave: Octaves.First,
    note: Notes[3],
    sound: require("../assets/sounds/new/Eb1.mp3"),
  },
  {
    index: 16,
    key: 19,
    octave: Octaves.Second,
    note: Notes[3],
    sound: require("../assets/sounds/new/Eb2.mp3"),
  },
  {
    index: 28,
    key: 20,
    octave: Octaves.Third,
    note: Notes[3],
    sound: require("../assets/sounds/new/Eb3.mp3"),
  },
  {
    index: 40,
    key: 21,
    octave: Octaves.Fourth,
    note: Notes[3],
    sound: require("../assets/sounds/new/Eb4.mp3"),
  },
  {
    index: 52,
    key: 22,
    octave: Octaves.Fifth,
    note: Notes[3],
    sound: require("../assets/sounds/new/Eb5.mp3"),
  },
  {
    index: 64,
    key: 23,
    octave: Octaves.Sixth,
    note: Notes[3],
    sound: require("../assets/sounds/new/Eb6.mp3"),
  },
  {
    index: 5,
    key: 24,
    octave: Octaves.First,
    note: Notes[4],
    sound: require("../assets/sounds/new/E1.mp3"),
  },
  {
    index: 17,
    key: 25,
    octave: Octaves.Second,
    note: Notes[4],
    sound: require("../assets/sounds/new/E2.mp3"),
  },
  {
    index: 29,
    key: 26,
    octave: Octaves.Third,
    note: Notes[4],
    sound: require("../assets/sounds/new/E3.mp3"),
  },
  {
    index: 41,
    key: 27,
    octave: Octaves.Fourth,
    note: Notes[4],
    sound: require("../assets/sounds/new/E4.mp3"),
  },
  {
    index: 53,
    key: 28,
    octave: Octaves.Fifth,
    note: Notes[4],
    sound: require("../assets/sounds/new/E5.mp3"),
  },
  {
    index: 65,
    key: 29,
    octave: Octaves.Sixth,
    note: Notes[4],
    sound: require("../assets/sounds/new/E6.mp3"),
  },
  {
    index: 6,
    key: 30,
    octave: Octaves.First,
    note: Notes[5],
    sound: require("../assets/sounds/new/F1.mp3"),
  },
  {
    index: 18,
    key: 31,
    octave: Octaves.Second,
    note: Notes[5],
    sound: require("../assets/sounds/new/F2.mp3"),
  },
  {
    index: 30,
    key: 32,
    octave: Octaves.Third,
    note: Notes[5],
    sound: require("../assets/sounds/new/F3.mp3"),
  },
  {
    index: 42,
    key: 33,
    octave: Octaves.Fourth,
    note: Notes[5],
    sound: require("../assets/sounds/new/F4.mp3"),
  },
  {
    index: 54,
    key: 34,
    octave: Octaves.Fifth,
    note: Notes[5],
    sound: require("../assets/sounds/new/F5.mp3"),
  },
  {
    index: 66,
    key: 35,
    octave: Octaves.Sixth,
    note: Notes[5],
    sound: require("../assets/sounds/new/F6.mp3"),
  },
  {
    index: 8,
    key: 36,
    octave: Octaves.First,
    note: Notes[6],
    sound: require("../assets/sounds/new/Gb1.mp3"),
  },
  {
    index: 19,
    key: 37,
    octave: Octaves.Second,
    note: Notes[6],
    sound: require("../assets/sounds/new/Gb2.mp3"),
  },
  {
    index: 31,
    key: 38,
    octave: Octaves.Third,
    note: Notes[6],
    sound: require("../assets/sounds/new/Gb3.mp3"),
  },
  {
    index: 43,
    key: 39,
    octave: Octaves.Fourth,
    note: Notes[6],
    sound: require("../assets/sounds/new/Gb4.mp3"),
  },
  {
    index: 55,
    key: 40,
    octave: Octaves.Fifth,
    note: Notes[6],
    sound: require("../assets/sounds/new/Gb5.mp3"),
  },
  {
    index: 67,
    key: 41,
    octave: Octaves.Sixth,
    note: Notes[6],
    sound: require("../assets/sounds/new/Gb6.mp3"),
  },
  {
    index: 9,
    key: 42,
    octave: Octaves.First,
    note: Notes[7],
    sound: require("../assets/sounds/new/G1.mp3"),
  },
  {
    index: 20,
    key: 43,
    octave: Octaves.Second,
    note: Notes[7],
    sound: require("../assets/sounds/new/G2.mp3"),
  },
  {
    index: 32,
    key: 44,
    octave: Octaves.Third,
    note: Notes[7],
    sound: require("../assets/sounds/new/G3.mp3"),
  },
  {
    index: 44,
    key: 45,
    octave: Octaves.Fourth,
    note: Notes[7],
    sound: require("../assets/sounds/new/G4.mp3"),
  },
  {
    index: 56,
    key: 46,
    octave: Octaves.Fifth,
    note: Notes[7],
    sound: require("../assets/sounds/new/G5.mp3"),
  },
  {
    index: 68,
    key: 47,
    octave: Octaves.Sixth,
    note: Notes[7],
    sound: require("../assets/sounds/new/G6.mp3"),
  },
  {
    index: 2,
    key: 48,
    octave: Octaves.First,
    note: Notes[8],
    sound: require("../assets/sounds/new/Ab1.mp3"),
  },
  {
    index: 21,
    key: 49,
    octave: Octaves.Second,
    note: Notes[8],
    sound: require("../assets/sounds/new/Ab2.mp3"),
  },
  {
    index: 33,
    key: 50,
    octave: Octaves.Third,
    note: Notes[8],
    sound: require("../assets/sounds/new/Ab3.mp3"),
  },
  {
    index: 45,
    key: 51,
    octave: Octaves.Fourth,
    note: Notes[8],
    sound: require("../assets/sounds/new/Ab4.mp3"),
  },
  {
    index: 57,
    key: 52,
    octave: Octaves.Fifth,
    note: Notes[8],
    sound: require("../assets/sounds/new/Ab5.mp3"),
  },
  {
    index: 69,
    key: 53,
    octave: Octaves.Sixth,
    note: Notes[8],
    sound: require("../assets/sounds/new/Ab6.mp3"),
  },
  {
    index: 10,
    key: 54,
    octave: Octaves.First,
    note: Notes[9],
    sound: require("../assets/sounds/new/A1.mp3"),
  },
  {
    index: 22,
    key: 55,
    octave: Octaves.Second,
    note: Notes[9],
    sound: require("../assets/sounds/new/A2.mp3"),
  },
  {
    index: 34,
    key: 56,
    octave: Octaves.Third,
    note: Notes[9],
    sound: require("../assets/sounds/new/A3.mp3"),
  },
  {
    index: 46,
    key: 57,
    octave: Octaves.Fourth,
    note: Notes[9],
    sound: require("../assets/sounds/new/A4.mp3"),
  },
  {
    index: 58,
    key: 58,
    octave: Octaves.Fifth,
    note: Notes[9],
    sound: require("../assets/sounds/new/A5.mp3"),
  },
  {
    index: 70,
    key: 59,
    octave: Octaves.Sixth,
    note: Notes[9],
    sound: require("../assets/sounds/new/A6.mp3"),
  },
  {
    index: 11,
    key: 60,
    octave: Octaves.First,
    note: Notes[10],
    sound: require("../assets/sounds/new/Bb1.mp3"),
  },
  {
    index: 23,
    key: 61,
    octave: Octaves.Second,
    note: Notes[10],
    sound: require("../assets/sounds/new/Bb2.mp3"),
  },
  {
    index: 35,
    key: 62,
    octave: Octaves.Third,
    note: Notes[10],
    sound: require("../assets/sounds/new/Bb3.mp3"),
  },
  {
    index: 47,
    key: 63,
    octave: Octaves.Fourth,
    note: Notes[10],
    sound: require("../assets/sounds/new/Bb4.mp3"),
  },
  {
    index: 59,
    key: 64,
    octave: Octaves.Fifth,
    note: Notes[10],
    sound: require("../assets/sounds/new/Bb5.mp3"),
  },
  {
    index: 71,
    key: 65,
    octave: Octaves.Sixth,
    note: Notes[10],
    sound: require("../assets/sounds/new/Bb6.mp3"),
  },
  {
    index: 12,
    key: 66,
    octave: Octaves.First,
    note: Notes[11],
    sound: require("../assets/sounds/new/B1.mp3"),
  },
  {
    index: 24,
    key: 67,
    octave: Octaves.Second,
    note: Notes[11],
    sound: require("../assets/sounds/new/B2.mp3"),
  },
  {
    index: 36,
    key: 68,
    octave: Octaves.Third,
    note: Notes[11],
    sound: require("../assets/sounds/new/B3.mp3"),
  },
  {
    index: 48,
    key: 69,
    octave: Octaves.Fourth,
    note: Notes[11],
    sound: require("../assets/sounds/new/B4.mp3"),
  },
  {
    index: 60,
    key: 70,
    octave: Octaves.Fifth,
    note: Notes[11],
    sound: require("../assets/sounds/new/B5.mp3"),
  },
  {
    index: 72,
    key: 71,
    octave: Octaves.Sixth,
    note: Notes[11],
    sound: require("../assets/sounds/new/B6.mp3"),
  },
];
